# Generated by Django 4.1.3 on 2022-12-12 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_to',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sent_from',
            new_name='sender',
        ),
    ]
